%let outpath	=&dir_rpt.\92.RST;


PROC EXPORT DATA= MART.RST_CRM_RWA_FACT_&st_Rptmth.
            OUTFILE= "&outpath.\RST_FACT_&st_Rptmth..csv" 
            DBMS=csv REPLACE;
RUN;



/* For FMG to reconcile AFS portfolio */

data MART.AFS_ST_RWA_for_FMG_&st_Rptmth.(rename=(
	CRM_ST1=APP_CRM_AMT_HKE_STRESSED
	RW_ST1=APPL_RISK_WEIGHT_STRESSED
	RWA_ST1=RISK_WEIGHTED_AMT_HKE_STRESSED
	));
	set mart.rst_00_base_&st_Rptmth.; 
	where FLAG_DELETE=. and FLAG_ELIM_COMBIN=. and FLAG_ELIM_CONSOL=.;
	if substr(ICAAP_PROD_CD,1,3)="AFS" or ICAAP_PROD_CD="Securities REPO";
	keep
	AS_OF_DT
	ENTITY
	APPL_CD
	PROD_SYS_CD
	ACCT_ID
	ORIG_PORT_CD
	PORT_CD
	ACCT_PROD
	CURR_CD
	BR
	CUST_SEC_ID
	CUST_BK_GROUP
	GROUP_ID
	GROUP_NAME
	GROUP_TURNOVER
	CUST_TYP_CD
	PRIM_OFF
	CUST_SIC_CD
	COUNTRY_CD
	CLS_ACCT_ID
	APPLIC_CD
	APPLIC_ACCT_ID
	FAC_REF
	FAC_TYP
	FAC_USAGE_CD
	PROD_SYS_REF
	CUR_BAL_ON
	CUR_BAL_ON_HKE
	CUR_BAL_OFF
	CUR_BAL_OFF_HKE
	UNPAID_INT_ACCR
	UNPAID_INT_ACCR_HKE
	TOT_EXP_AMT_HKE
	ORIG_CRM_AMT_HKE
	ORIG_RISK_WEIGHT
	APPL_CRM_AMT_HKE
	APPL_RISK_WEIGHT
	RISK_WEIGHTED_AMT_HKE
	ICAAP_CUST_SEC_ID
	ICAAP_BUS_UNIT
	BAL_OGL_ACCT
	OGL_PROD_CD
	ALCO_PROD_CD
	ICAAP_PROD_CD
	ON_OFF_IND
	RC_CD
	ICAAP_TEAM_CD
	ICAAP_TEAM_DESC
	ICAAP_RC_TEAM_CD
	ICAAP_CNTR_TYP
	ICAAP_CNTR_TYP_DESC
	CRM_ST1
	RW_ST1
	RWA_ST1
	;
run;

PROC EXPORT DATA= MART.AFS_ST_RWA_for_FMG_&st_Rptmth.
            OUTFILE= "&outpath.\AFS_ST_RWA_for_FMG_&st_Rptmth..csv" 
            DBMS=csv REPLACE;
RUN;

