data st_parameter;
	set siw.xls_rp_parm_&st_Rptmth.;
	where effective_from <=&dt_Rptmth.<=effective_to;
	/* ****************************************** */
	if SEGMENT="FI" then do;
		if TYPE="NOTCH" then do;
			call symput("fi_notch0",base);
			call symput("fi_notch1",mild);
			call symput("fi_notch2",medium);
			call symput("fi_notch3",severe);
		end;
		if TYPE="LGD" then do;
			call symput("fi_lgd0",base);
			call symput("fi_lgd1",mild);
			call symput("fi_lgd2",medium);
			call symput("fi_lgd3",severe);
		end;
	end;
	/* ****************************************** */
	if upcase(SEGMENT)="HK" then do;
		if TYPE="PROPERTY_PRICE_YOY" then do;
			call symput("hkccl_yoy0",base);
			call symput("hkccl_yoy1",mild);
			call symput("hkccl_yoy2",medium);
			call symput("hkccl_yoy3",severe);
		end;
		if TYPE="PROPERTY_COLL_HAIRCUT" then do;
			call symput("hk_haircut0",base);
			call symput("hk_haircut1",mild);
			call symput("hk_haircut2",medium);
			call symput("hk_haircut3",severe);
		end;
	end;
	/* ****************************************** */
	if upcase(SEGMENT)="CN" then do;
		if TYPE="PROPERTY_PRICE_YOY" then do;
			call symput("cnccl_yoy0",base);
			call symput("cnccl_yoy1",mild);
			call symput("cnccl_yoy2",medium);
			call symput("cnccl_yoy3",severe);
		end;
		if TYPE="PROPERTY_COLL_HAIRCUT" then do;
			call symput("cn_haircut0",base);
			call symput("cn_haircut1",mild);
			call symput("cn_haircut2",medium);
			call symput("cn_haircut3",severe);
		end;
	end;
	/* ****************************************** */
	if upcase(SEGMENT)="HK_PRTY_INV_DEV" then do;
		if TYPE="LOAN_GROWTH" then do;
			call symput("piv_lgth0",base);
			call symput("piv_lgth1",mild);
			call symput("piv_lgth2",medium);
			call symput("piv_lgth3",severe);
		end;
		if TYPE="NPLCOV" then do;
			call symput("piv_nplcov0",base);
			call symput("piv_nplcov1",mild);
			call symput("piv_nplcov2",medium);
			call symput("piv_nplcov3",severe);
		end;
		if TYPE="NPL" then do;
			call symput("piv_npl0",base);
			call symput("piv_npl1",mild);
			call symput("piv_npl2",medium);
			call symput("piv_npl3",severe);
		end;
		if TYPE="LGD" then do;
			call symput("piv_lgd0",base);
			call symput("piv_lgd1",mild);
			call symput("piv_lgd2",medium);
			call symput("piv_lgd3",severe);
		end;
	end;
	/* ****************************************** */
	if upcase(SEGMENT)="HK_RML" then do;
		if TYPE="LOAN_GROWTH" then do;
			call symput("rml_lgth0",base);
			call symput("rml_lgth1",mild);
			call symput("rml_lgth2",medium);
			call symput("rml_lgth3",severe);
		end;
		if TYPE="NPLCOV" then do;
			call symput("rml_nplcov0",base);
			call symput("rml_nplcov1",mild);
			call symput("rml_nplcov2",medium);
			call symput("rml_nplcov3",severe);
		end;
		if TYPE="NPL" then do;
			call symput("rml_npl0",base);
			call symput("rml_npl1",mild);
			call symput("rml_npl2",medium);
			call symput("rml_npl3",severe);
		end;
		if TYPE="LGD" then do;
			call symput("rml_lgd0",base);
			call symput("rml_lgd1",mild);
			call symput("rml_lgd2",medium);
			call symput("rml_lgd3",severe);
		end;
	end;
	/* ****************************************** */
	if upcase(SEGMENT)="ALL_NBMCE" then do;
		if TYPE="LOAN_GROWTH" then do;
			call symput("nbmce_lgth0",base);
			call symput("nbmce_lgth1",mild);
			call symput("nbmce_lgth2",medium);
			call symput("nbmce_lgth3",severe);
		end;
		if TYPE="NPLCOV" then do;
			call symput("nbmce_nplcov0",base);
			call symput("nbmce_nplcov1",mild);
			call symput("nbmce_nplcov2",medium);
			call symput("nbmce_nplcov3",severe);
		end;
		if TYPE="NPL" then do;
			call symput("nbmce_npl0",base);
			call symput("nbmce_npl1",mild);
			call symput("nbmce_npl2",medium);
			call symput("nbmce_npl3",severe);
		end;
		if TYPE="LGD" then do;
			call symput("nbmce_lgd0",base);
			call symput("nbmce_lgd1",mild);
			call symput("nbmce_lgd2",medium);
			call symput("nbmce_lgd3",severe);
		end;
	end;
	/* ****************************************** */
	if upcase(SEGMENT)="ALL_CUST_LOAN" then do;
		if TYPE="LOAN_GROWTH" then do;
			call symput("oth_lgth0",base);
			call symput("oth_lgth1",mild);
			call symput("oth_lgth2",medium);
			call symput("oth_lgth3",severe);
		end;
		if TYPE="NPLCOV" then do;
			call symput("oth_nplcov0",base);
			call symput("oth_nplcov1",mild);
			call symput("oth_nplcov2",medium);
			call symput("oth_nplcov3",severe);
		end;
		if TYPE="NPL" then do;
			call symput("oth_npl0",base);
			call symput("oth_npl1",mild);
			call symput("oth_npl2",medium);
			call symput("oth_npl3",severe);
		end;
		if TYPE="LGD" then do;
			call symput("oth_lgd0",base);
			call symput("oth_lgd1",mild);
			call symput("oth_lgd2",medium);
			call symput("oth_lgd3",severe);
		end;
	end;
	if upcase(SEGMENT)="DERIV" then do;
		if TYPE="CURR_EXP_MULTIPLIER" then do;
			call symput("der_multi0",base);
			call symput("der_multi1",mild);
			call symput("der_multi2",medium);
			call symput("der_multi3",severe);
		end;
		if TYPE="NPL" then do;
			call symput("der_npl0",base);
			call symput("der_npl1",mild);
			call symput("der_npl2",medium);
			call symput("der_npl3",severe);
		end;
	end;
run;

%put &fi_notch0.		&fi_notch1. 			&fi_notch2. 		&fi_notch3.;
%put &hkccl_yoy0. 		&hkccl_yoy1.			&hkccl_yoy2.		&hkccl_yoy3.;
%put &cnccl_yoy0.		&cnccl_yoy1.			&cnccl_yoy2.		&cnccl_yoy3.;
%put &hk_haircut0.		&hk_haircut1.			&hk_haircut2.		&hk_haircut3.;
%put &cn_haircut0.		&cn_haircut1.			&cn_haircut2.		&cn_haircut3.;

%put &piv_lgth0.		&piv_lgth1.				&piv_lgth2.			&piv_lgth3.;
%put &piv_nplcov0.		&piv_nplcov1.			&piv_nplcov2.		&piv_nplcov3.;
%put &piv_npl0.			&piv_npl1.				&piv_npl2.			&piv_npl3.;
%put &piv_lgd0.			&piv_lgd1.				&piv_lgd2.			&piv_lgd3.;

%put &rml_lgth0.		&rml_lgth1.				&rml_lgth2.			&rml_lgth3.;
%put &rml_nplcov0.		&rml_nplcov1.			&rml_nplcov2.		&rml_nplcov3.;
%put &rml_npl0.			&rml_npl1.				&rml_npl2.			&rml_npl3.;
%put &rml_lgd0.			&rml_lgd1.				&rml_lgd2.			&rml_lgd3.;

%put &nbmce_lgth0.		&nbmce_lgth1.			&nbmce_lgth2.		&nbmce_lgth3.;
%put &nbmce_nplcov0.	&nbmce_nplcov1.			&nbmce_nplcov2.		&nbmce_nplcov3.;
%put &nbmce_npl0.		&nbmce_npl1.			&nbmce_npl2.		&nbmce_npl3.;
%put &nbmce_lgd0.		&nbmce_lgd1.			&nbmce_lgd2.		&nbmce_lgd3.;

%put &oth_lgth0.		&oth_lgth1.				&oth_lgth2.			&oth_lgth3.;
%put &oth_nplcov0.		&oth_nplcov1.			&oth_nplcov2.		&oth_nplcov3.;
%put &oth_npl0.			&oth_npl1.				&oth_npl2.			&oth_npl3.;
%put &oth_lgd0.			&oth_lgd1.				&oth_lgd2.			&oth_lgd3.;

%put &der_multi0.		&der_multi1.			&der_multi2.		&der_multi2.;
%put &der_npl0.			&der_npl1.				&der_npl2.			&der_npl3.;
